name: build-docs

# Only run this when the master branch changes
on:
  pull_request:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        python3 -m pip install pdoc matplotlib numpy scipy wheel setuptools poetry pytest
        python3 -m pip install .

    # Build the site
    - name: Build the site
      run: |
        bash generate_docs.sh

    # If we've pushed to master with a tag, push the book's HTML to github-pages
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
        fi
    - name: GitHub Pages action
      if: steps.check-tag.outputs.match == 'true'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
