name: Publish tagged version to PyPI

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fitk
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      #----------------------------------------------
      #        poetry setup
      #----------------------------------------------
      - name: Setup poetry
        uses: snok/install-poetry@v1
          with:
            version: 1.4.2
            virtualenvs-create: true
            virtualenvs-in-project: true

      - name: Build wheel and tarball
        run: poetry build --no-interaction

      - name: Publish package distributions to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
