name: test

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      #----------------------------------------------
      #        load pip cache if cache exists
      #----------------------------------------------
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      #----------------------------------------------
      #          install and run linters
      #----------------------------------------------
      - run: python -m pip install black
      - run: |
          black . --check
  test:
    needs: linting
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        numpy-version: ["1.16.0"]
        scipy-version: ["1.2.0"]
        matplotlib-version: ["3.3.2"]
        python-version: ["3.7", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Make a venv
        run: |
          python -m venv .venv
      - name: Install dev dependencies
        run: |
          source .venv/bin/activate
          python -m pip install setuptools wheel pytest coverage git+https://github.com/jcgoran/cosmicfish@feature/pip-install
      #----------------------------------------------
      #    add matrix specifics and run test suite
      #----------------------------------------------
      - name: Install numpy ${{ matrix.numpy-version }}, scipy ${{ matrix.scipy-version }}, matplotlib ${{ matrix.matplotlib-version }}
        run: |
          source .venv/bin/activate
          python -m pip install "numpy==${{ matrix.numpy-version }}" "scipy==${{ matrix.scipy-version }}" "matplotlib==${{ matrix.matplotlib-version }}"
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pip install .
          pytest tests/
          coverage report
